--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      DATA MODEL
--
-- Date Created : Thursday, February 13, 2025 19:38:07
-- Target DBMS : Snowflake
--

-- 
-- TABLE: CRIME_FACT 
--

CREATE TABLE CRIME_FACT(
    CF_SK          VARCHAR(50)     NOT NULL,
    LOCATION_SK    VARCHAR(50)     NOT NULL,
    CRIMES_SK      VARCHAR(50)     NOT NULL,
    CRIMINAL_SK    VARCHAR(50)     NOT NULL,
    DATE_SK        VARCHAR(50)     NOT NULL,
    ARRESTS_SK     VARCHAR(100)    NOT NULL,
    DI_JOB_ID      VARCHAR(100),
    DI_JOB_DATE    DATE,
    CONSTRAINT PK5 PRIMARY KEY (CF_SK, LOCATION_SK, CRIMES_SK, CRIMINAL_SK, DATE_SK, ARRESTS_SK) 
)
;



-- 
-- TABLE: DIM_ARRESTS 
--

CREATE TABLE DIM_ARRESTS(
    ARRESTS_SK             VARCHAR(100)     NOT NULL,
    ARREST_ID              VARCHAR(50)      NOT NULL,
    ARREST_BOROUGH         VARCHAR(10),
    ARREST_PRECINCT        VARCHAR(10),
    ARREST_JURIDISCTION    NUMBER(10, 0),
    DI_JOB_ID              VARCHAR(100),
    DI_JOB_DT              VARCHAR(100),
    CONSTRAINT ARRESTS_SK PRIMARY KEY (ARRESTS_SK) 
)
;



-- 
-- TABLE: DIM_CRIMES 
--

CREATE TABLE DIM_CRIMES(
    CRIMES_SK       VARCHAR(50)     NOT NULL,
    CRIMES_ID       VARCHAR(50),
    PD_DESC         CHAR(100),
    OFFENSE_CAT     VARCHAR(100),
    LAW_CODE        VARCHAR(50),
    LAW_CATEGORY    VARCHAR(50),
    DI_JOB_ID       VARCHAR(50),
    DI_JOB_DATE     DATE,
    CONSTRAINT PK_CRIMES_SK PRIMARY KEY (CRIMES_SK) 
)
;



-- 
-- TABLE: DIM_CRIMINAL 
--

CREATE TABLE DIM_CRIMINAL(
    CRIMINAL_SK    VARCHAR(50)     NOT NULL,
    CRIMINAL_ID    VARCHAR(50),
    AGE            VARCHAR(10),
    DI_JOB_ID      VARCHAR(100),
    DI_JOB_DATE    DATE,
    SEX            CHAR(1),
    RACE           VARCHAR(50),
    CONSTRAINT PK3 PRIMARY KEY (CRIMINAL_SK) 
)
;



-- 
-- TABLE: DIM_DATE 
--

CREATE TABLE DIM_DATE(
    DATE_SK        VARCHAR(50)     NOT NULL,
    DAY_ABRV       VARCHAR(3),
    DAY_NUM        NUMBER(2, 0),
    WEEK_NUM       NUMBER(2, 0),
    MONTH_ABRV     VARCHAR(3),
    DATE_ID        VARCHAR(50),
    DT             DATE,
    MONTH_NUM      NUMBER(2, 0),
    QTR_NUM        NUMBER(2, 0),
    YEAR_NUM       NUMBER(4, 0),
    DI_JOB_ID      VARCHAR(100),
    DI_JOB_DATE    DATE,
    CONSTRAINT PK4 PRIMARY KEY (DATE_SK) 
)
;



-- 
-- TABLE: DIM_LOCATION 
--

CREATE TABLE DIM_LOCATION(
    LOCATION_SK     VARCHAR(50)        NOT NULL,
    LOCATION_ID     VARCHAR(50),
    LONGITUDE       DECIMAL(100, 0),
    LATITUDE        DECIMAL(100, 0),
    GEOREFERENCE    VARCHAR(100),
    DI_JOB_ID       VARCHAR(100),
    DI_JOB_DATE     DATE,
    CONSTRAINT PK2 PRIMARY KEY (LOCATION_SK) 
)
;



-- 
-- TABLE: CRIME_FACT 
--

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_LOCATION11 
    FOREIGN KEY (LOCATION_SK)
    REFERENCES DIM_LOCATION(LOCATION_SK)
;

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_CRIMES21 
    FOREIGN KEY (CRIMES_SK)
    REFERENCES DIM_CRIMES(CRIMES_SK)
;

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_CRIMINAL31 
    FOREIGN KEY (CRIMINAL_SK)
    REFERENCES DIM_CRIMINAL(CRIMINAL_SK)
;

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_DATE41 
    FOREIGN KEY (DATE_SK)
    REFERENCES DIM_DATE(DATE_SK)
;

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_ARRESTS51 
    FOREIGN KEY (ARRESTS_SK)
    REFERENCES DIM_ARRESTS(ARRESTS_SK)
;


