create or replace warehouse NYPD_WH warehouse_size='XSMALL';
create or replace database NYPD_DB;
create or replace schema NYPD_DB.NYPD_SCHEMA;
create or replace role TEMP_ROLE;

grant ownership on database NYPD_DB to role ACCOUNTADMIN;

GRANT USAGE ON WAREHOUSE NYPD_WH TO ROLE TEMP_ROLE;

grant usage on database NYPD_DB to role TEMP_ROLE;

grant ownership on schema NYPD_DB.NYPD_SCHEMA to role TEMP_ROLE;
grant usage on schema NYPD_DB.NYPD_SCHEMA to role TEMP_ROLE;

create or replace user TEMP_USER password='snowflake123#' default_role=TEMP_ROLE default_warehouse=NYPD_WH;

grant role TEMP_ROLE to user TEMP_USER;
GRANT OWNERSHIP ON SCHEMA NYPD_DB.NYPD_SCHEMA TO ROLE TEMP_ROLE;



USE DATABASE NYPD_DB;
USE SCHEMA NYPD_DB.NYPD_SCHEMA;

GRANT USAGE ON DATABASE NYPD_DB TO ROLE TEMP_ROLE;
GRANT USAGE ON SCHEMA NYPD_DB.NYPD_SCHEMA TO ROLE TEMP_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA NYPD_DB.NYPD_SCHEMA TO ROLE TEMP_ROLE;
SHOW GRANTS TO ROLE TEMP_ROLE;
SHOW GRANTS ON SCHEMA NYPD_DB.NYPD_SCHEMA;

USE ROLE TEMP_ROLE;


CREATE TABLE CRIME_FACT(
    CF_SK          VARCHAR(50)     NOT NULL,
    LOCATION_SK    VARCHAR(50)     NOT NULL,
    CRIMES_SK      VARCHAR(50)     NOT NULL,
    CRIMINAL_SK    VARCHAR(50)     NOT NULL,
    DATE_SK        VARCHAR(50)     NOT NULL,
    ARRESTS_SK     VARCHAR(100)    NOT NULL,
    DI_JOB_ID      VARCHAR(100),
    DI_JOB_DATE    DATE,
    CONSTRAINT PK5 PRIMARY KEY (CF_SK, LOCATION_SK, CRIMES_SK, CRIMINAL_SK, DATE_SK, ARRESTS_SK) 
)
;



-- 
-- TABLE: DIM_ARRESTS 
--

CREATE TABLE DIM_ARRESTS(
    ARRESTS_SK             VARCHAR(100)     NOT NULL,
    ARREST_ID              VARCHAR(50)      NOT NULL,
    ARREST_BOROUGH         VARCHAR(10),
    ARREST_PRECINCT        VARCHAR(10),
    ARREST_JURIDISCTION    NUMBER(10, 0),
    DI_JOB_ID              VARCHAR(100),
    DI_JOB_DT              VARCHAR(100),
    CONSTRAINT ARRESTS_SK PRIMARY KEY (ARRESTS_SK) 
)
;



-- 
-- TABLE: DIM_CRIMES 
--

CREATE TABLE DIM_CRIMES(
    CRIMES_SK       VARCHAR(50)     NOT NULL,
    CRIMES_ID       VARCHAR(50),
    PD_DESC         CHAR(100),
    OFFENSE_CAT     VARCHAR(100),
    LAW_CODE        VARCHAR(50),
    LAW_CATEGORY    VARCHAR(50),
    DI_JOB_ID       VARCHAR(50),
    DI_JOB_DATE     DATE,
    CONSTRAINT PK_CRIMES_SK PRIMARY KEY (CRIMES_SK) 
)
;



-- 
-- TABLE: DIM_CRIMINAL 
--

CREATE TABLE DIM_CRIMINAL(
    CRIMINAL_SK    VARCHAR(50)     NOT NULL,
    CRIMINAL_ID    VARCHAR(50),
    AGE            VARCHAR(10),
    DI_JOB_ID      VARCHAR(100),
    DI_JOB_DATE    DATE,
    SEX            CHAR(1),
    RACE           VARCHAR(50),
    CONSTRAINT PK3 PRIMARY KEY (CRIMINAL_SK) 
)
;



-- 
-- TABLE: DIM_DATE 
--

CREATE TABLE DIM_DATE(
    DATE_SK        VARCHAR(50)     NOT NULL,
    DAY_ABRV       VARCHAR(3),
    DAY_NUM        NUMBER(2, 0),
    WEEK_NUM       NUMBER(2, 0),
    MONTH_ABRV     VARCHAR(3),
    DATE_ID        VARCHAR(50),
    DT             DATE,
    MONTH_NUM      NUMBER(2, 0),
    QTR_NUM        NUMBER(2, 0),
    YEAR_NUM       NUMBER(4, 0),
    DI_JOB_ID      VARCHAR(100),
    DI_JOB_DATE    DATE,
    CONSTRAINT PK4 PRIMARY KEY (DATE_SK) 
)
;



-- 
-- TABLE: DIM_LOCATION 
--

CREATE TABLE DIM_LOCATION(
    LOCATION_SK     VARCHAR(50)        NOT NULL,
    LOCATION_ID     VARCHAR(50),
    LONGITUDE       DECIMAL(100, 0),
    LATITUDE        DECIMAL(100, 0),
    GEOREFERENCE    VARCHAR(100),
    DI_JOB_ID       VARCHAR(100),
    DI_JOB_DATE     DATE,
    CONSTRAINT PK2 PRIMARY KEY (LOCATION_SK) 
)
;



-- 
-- TABLE: CRIME_FACT 
--

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_LOCATION1 
    FOREIGN KEY (LOCATION_SK)
    REFERENCES DIM_LOCATION(LOCATION_SK)
;

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_CRIMES2 
    FOREIGN KEY (CRIMES_SK)
    REFERENCES DIM_CRIMES(CRIMES_SK)
;

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_CRIMINAL3 
    FOREIGN KEY (CRIMINAL_SK)
    REFERENCES DIM_CRIMINAL(CRIMINAL_SK)
;

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_DATE4 
    FOREIGN KEY (DATE_SK)
    REFERENCES DIM_DATE(DATE_SK)
;

ALTER TABLE CRIME_FACT ADD CONSTRAINT RefDIM_ARRESTS5 
    FOREIGN KEY (ARRESTS_SK)
    REFERENCES DIM_ARRESTS(ARRESTS_SK)
;


create or replace table NYPD_SCHEMA.NYPD_STAGE_TABLE(
    ARREST_KEY VARCHAR(100), 
    ARREST_DATE VARCHAR(100),
    PD_CD VARCHAR(100),
    PD_DESC VARCHAR(100),
    KY_CD VARCHAR(100),
    OFFENSE_DESCRIPTION VARCHAR(100),
    LAW_CODE VARCHAR(100),
    LAW_CAT_CD VARCHAR(100),
    BOROUGH VARCHAR(100),
    PRECINCT VARCHAR(100),
    JURISDICTION_CODE VARCHAR(100),
    AGE_GROUP VARCHAR(100),
    SEX VARCHAR(100),
    RACE VARCHAR(100),
    X_COORD VARCHAR(100),
    Y_COORD VARCHAR(100),
    LATITUDE VARCHAR(100),
    LONGITUDE VARCHAR(100),
    NEW_GEOREFERENCED_ID VARCHAR(100),
    dt_job_id STRING(100),    
    dt_job_date DATE     
);

select * from NYPD_SCHEMA.NYPD_STAGE_TABLE;